# Generated by Django 3.2.12 on 2022-02-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_relationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=225)),
                ('phone_num', models.IntegerField(default='+')),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=220)),
                ('message', models.TextField()),
            ],
        ),
    ]
